### ISSUE TITLE
友谊

### ISSUE THREAD

**Issue by rastaman111** [zhiyongzou/iRead#1]
你好！
我不知道您说什么语言，Google用中文说）

我对您作为OpenSourse的工作感兴趣，您正在开发它还是到达终点？

由于我正在开发应用程序，因此需要一个简单的EPUB Reader

**Comment by rastaman111** [comment]
我注意到您的项目无法正常运作
例如：
1）在书中看不到图片
2）没有看到目录
3）由于看不见的原因而无法打开书本

**Comment by zhiyongzou** [comment]
Make sure build configuration is DEBUG,  I can't open your link. In addition, You can make a breakpoint in `addTestBook(name: String)` to confirm whether the book is loaded successfully.

**Comment by rastaman111** [comment]
Yes, that's what I do, I added a book to the project and called it.

In the photo video that one book is not parsed and plus the picture of the book does not come as 1 page and its description

![image](https://user-images.githubusercontent.com/15727518/99147511-a75e7c00-2692-11eb-8c69-f56a6aff95ea.jpeg)
![image](https://user-images.githubusercontent.com/15727518/99147518-bd6c3c80-2692-11eb-9e56-1a8fe86031bb.png)
![image](https://user-images.githubusercontent.com/15727518/99147525-ceb54900-2692-11eb-8110-79072be1e1d6.jpeg)

**Comment by zhiyongzou** [comment]
is The Silver Chair open successfully? What is the content of xx.ncx file.
![Xnip2020-11-14_21-47-16](https://user-images.githubusercontent.com/18436091/99148509-ff14db80-26c2-11eb-913b-3c4a8f56d21b.jpg)
![Xnip2020-11-14_21-48-16](https://user-images.githubusercontent.com/18436091/99148536-210e5e00-26c3-11eb-8bc1-0a90099a8794.jpg)

**Comment by zhiyongzou** [comment]
Check the contents of the unzipped book which path in sandbox documents folder

**Comment by rastaman111** [comment]
I added a book to the project itself and one of the rules is readable, and the other is not readable.  those 2 links won't open?

**Comment by zhiyongzou** [comment]
> I added a book to the project itself and one of the rules is readable, and the other is not readable. those 2 links won't open?

I guess there is a problem with the format of the book which is unreadable.  You can check  the unzipped book's NCX file

**Comment by rastaman111** [comment]
How can i find the ncx file on the file system?

**Comment by rastaman111** [comment]
[Архив.zip](https://github.com/zhiyongzou/iRead/files/5541332/default.zip)
Here are 2 books

**Comment by rastaman111** [comment]
![Uploading 99171345...]

**Comment by rastaman111** [comment]
here in this book, too, not the whole book is loaded

![image](https://user-images.githubusercontent.com/15727518/99171345-29918380-2719-11eb-999a-f19429916d7b.jpeg)
![image](https://user-images.githubusercontent.com/15727518/99171347-34e4af00-2719-11eb-8fb5-2c70f6aded7f.jpeg)

**Comment by zhiyongzou** [comment]
> here in this book, too, not the whole book is loaded
> 
> ![image](https://user-images.githubusercontent.com/15727518/99171345-29918380-2719-11eb-999a-f19429916d7b.jpeg)
> ![image](https://user-images.githubusercontent.com/15727518/99171347-34e4af00-2719-11eb-8fb5-2c70f6aded7f.jpeg)

The 2 books has sub-chapters,. If you want to load whole book, you can simply replace `tableOfContents` with `flatTableOfContents` ,These two propertys are in the `IRBook` class. In addition,  I will fix this problem later

**Comment by zhiyongzou** [comment]
The 2 books has sub-chapters,. If you want to load whole book, you can simply replace tableOfContents with flatTableOfContents ,These two propertys are in the IRBook class. In addition, I will fix this problem later
