### ISSUE TITLE
Upload book by wifi and AirDrop

### ISSUE THREAD

**Issue by rastaman111** [zhiyongzou/iRead#4]
![image](https://user-images.githubusercontent.com/15727518/100233416-c8e52080-2f3a-11eb-95d7-cdd0cfc1ea25.png)
![image](https://user-images.githubusercontent.com/15727518/100233426-cbe01100-2f3a-11eb-8448-6f4bf1ba5217.png)
![image](https://user-images.githubusercontent.com/15727518/100233435-cedb0180-2f3a-11eb-9a2a-50b9ba040356.png)
![image](https://user-images.githubusercontent.com/15727518/100233452-d26e8880-2f3a-11eb-8ce0-c705cb47d958.png)

**Comment by rastaman111** [comment]
this is a simple code for adding a book to the application, plus you need to specify a key pair in info.plist

**Comment by rastaman111** [comment]
here you can also check if they throw a zip file or folder, so as not to add all this, but immediately get ePub files

**Comment by rastaman111** [comment]
hello, I looked at your developer branch, you are not doing the import via airdrop.  You need to first: 
1. first accept the url 
2. check if there is a similar file in our directory with the name if there is before do file (index) if not then file 
3. check for exist after that you do not need 
4. the user can also send a folder  or a zip file from ePub and you need to get them from there (if you need a code, then I can throw off how to do it)

**Comment by zhiyongzou** [comment]
> hello, I looked at your developer branch, you are not doing the import via airdrop. You need to first:
> 
> 1. first accept the url
> 2. check if there is a similar file in our directory with the name if there is before do file (index) if not then file
> 3. check for exist after that you do not need
> 4. the user can also send a folder  or a zip file from ePub and you need to get them from there (if you need a code, then I can throw off how to do it)

Hi, this feature is being added. Welcome to contribute

**Comment by rastaman111** [comment]
hello, I did as on my project, but I need to finish it, this is the right decision, but you can simplify the process
[iRead-development.zip](https://github.com/zhiyongzou/iRead/files/5629665/iRead-development.zip)

**Comment by rastaman111** [comment]
@zhiyongzou 

hi, how did you figure it out?
